FROM node:lts-alpine

WORKDIR '/app'

RUN apk --update add git curl openssh nano
RUN npm install -g npm@latest

COPY package.json .

RUN npm install

COPY . .

ENV NODE_ENV development
ENV HOST 0.0.0.0

EXPOSE 3000

CMD ["npm","run","dev"]
